teste = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(teste))
print('É numérico? ', teste.isnumeric())
print('É composto só por letras?', teste.isalpha())
print('É alfanumérico? ', teste.isalnum())
print('Foi escrito tudo em caixa alta? ', teste.isupper())
print('Foi escrito tudo em minúsculo? ', teste.islower())
print('Só tem espaços? ', teste.isspace())
print('Está capitalizada? ', teste.istitle())
